125 update roadmap
astrogilda/tsbootstrap pull request #126
Opened 2024-04-06 23:32 UTC by astrogilda

# Pull Request Template

## Description

Updated `roadmap` in `README.md`. 
Added TODO points.
closes #125 
## Type of change

Please delete options that are not relevant.

- [ x] This change requires a documentation update

## Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

## Add All Contributors Command

Remember to acknowledge your contributions, replace `contribution_type` with your contribution (code, doc, etc.):

```plaintext
@all-contributors please add @<your-username> for <contribution_type>
```

2024-04-21 22:11 UTC, fkiraly requested changes
It seems like this PR accidentally contains commits from multiple PR. Accidental push?

Can you kindly untangle this?

2024-04-21 22:26 UTC, astrogilda commented
> It seems like this PR accidentally contains commits from multiple PR. Accidental push?
> 
> Can you kindly untangle this?

Just rebased against main, should be g2g!

2024-04-22 10:01 UTC, fkiraly commented on .github/workflows/release.yml
> +          packages-dir: wheelhouse/
unintended?

2024-04-22 10:02 UTC, fkiraly commented on src/tsbootstrap/base_bootstrap.py
> -
I think this will fail flake8 linting

2024-04-22 10:04 UTC, fkiraly requested changes
It still seems there are multiple changes in this PR unrelated to the roadmap, some of them appearing accidental?

I suggest moving anything that is not adding roadmap into separate PR and commenting, so at least it's clear that the changes are deliberate and not accidental.
(of course you can make any changes you like to your repo, I am just flagging the risk of accidentally breaking things without review)

Regarding the roadmap: I think it makes sense overall.
I feel it is a bit verbose though - personally, I prefer bullet point lists, with more extensive text possibly in a second section, or design documents.

I have also some ideas which are not necessary to add, but for consideration.

2024-04-22 10:05 UTC, fkiraly commented
> Just rebased against main, should be g2g!

My recommendation is merging from main. I know there are differring schools here, I just feel the risk for unintended reverts (like the above?) is less if you do things quickly.

2024-04-22 16:33 UTC, fkiraly commented
Some random ideas for roadmap:

### integration

* using arbitrary `sktime` forecaster in forecaster based bootstraps
* using `tsbootstrap` bootstraps to create a distribution or sampler-like object (`skpro` or `sktime` proba distribution over time series)


### boilerplate/sugar

* fractions for block lengths etc
* ability to pass `pd.DataFrame`. "core" behaviour is `np.ndarray`, but if `pd.DataFrame` is passed, produces the output to have same index and columns


### refactor

* there is some legacy entanglement of classes. These should be refactored to be "flatter".
* the block bootstraps look like they should be composites


### API extension

* update/stream
* panels and hierarchical data
* exogenous data (API supports but there is no logic except for forecasters)
* fittable or pretrained


### adjacent areas

* time series augmentation
* full proba models that can be sampled from
* time series data generation

2024-04-22 17:48 UTC, astrogilda commented on .github/workflows/release.yml
> +          packages-dir: wheelhouse/
nah, `ruff`s recommendation

2024-04-22 17:48 UTC, astrogilda commented on README.md
> +x1 = np.arrange(1, n_samples + 1).reshape(-1, 1)
yep! reverted

2024-04-22 21:33 UTC, fkiraly requested changes
still something weird going on with all files being changed.

2024-04-22 21:35 UTC, astrogilda commented
Hmm this is after reading against main.
Maybe let's focus on the readme.md file for now given the time constraints?

On Mon, Apr 22, 2024, 5:34 PM Franz Király ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> still something weird going on with all files being changed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/astrogilda/tsbootstrap/pull/126#pullrequestreview-2015841406>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFTOOHQXUOI5QDLEAABPU63Y6V65BAVCNFSM6AAAAABF2ZTWXOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMJVHA2DCNBQGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-22 23:07 UTC, fkiraly commented on .github/workflows/release.yml
> +          packages-dir: wheelhouse/
are both keywords valid?

2024-04-22 23:08 UTC, fkiraly commented on README.md
> +x1 = np.arrange(1, n_samples + 1).reshape(-1, 1)
does not look like it

2024-04-22 23:09 UTC, fkiraly requested changes
various changes issue still there, I think it's better to split.

Re roadmap, I think it would be better to move too verbose content somewher else, and have only an extra short bullet point list in the README.

One option is docs, another option is an issue, for 2024-2025 roadmap.

2024-04-23 12:30 UTC, fkiraly requested changes
Thanks, and for resolving the merge conflicts!

My suggestion would be to split this roadmap in two: a high-level, short part in the README, and an issue ("tsbootstrap roadmap 2024-2025" or similar) which the README links to.

E.g., high-level as follows

* **performance and scaling** - handling large datasets, distributed backend integration (dask, spark, ray), profiling/optimization
* **tuning and autoML** - adaptive block length, adaptive resampling, evaluation based parameter selection
* **real-time and stream data** - stream bootstraps, data update interface
* **stage 2 `sktime` integration** - evaluation module, datasets, benchmarks, `sktime` forecasters in bootstraps
* **API and capability extension** - panel/hierarchical data, exogenous data, update/stream, model state management
* **scope extension** (to be discussed) - time series augmentation, fully probabilistic models

Further details: [link to decompressed version]

2024-04-23 19:23 UTC, fkiraly approved these changes
Yes, that's nice - I also liked the longer version though, it had more detail.

I would still suggest to open an issue and link.

2024-04-23 19:25 UTC, astrogilda commented
it's linked in the updated readme.py

2024-04-23 19:30 UTC, astrogilda commented
Just tried, I guess you can't. I'll put it here.

2024-04-23 19:43 UTC, fkiraly commented
you could just add an ordinary link, like `[name](URL)`

2024-04-23 19:52 UTC, merged